export enum ActionType {
    ADD_ACCOUNT_SUCCESSS = "ADD_ACCOUNT",
    ADD_ACCOUNT_FAIL = "ADD_ACCOUNT_FAIL",
    REMOVE_ACCOUNT_SUCCESS = "REMOVE_ACCOUNT",
    REMOVE_ACCOUNT_FAIL = "REMOVE_ACCOUNT_FAIL",
    UPDATE_ACCOUNT_SUCCESS = "UPDATE_ACCOUNT_SUCCESS",
    UPDATE_ACCOUNT_FAIL = "UPDATE_ACCOUNT_FAIL",
    UPDATE_ACCOUNT_PENDING = "UPDATE_ACCOUNT_PENDING"
}